name: "Deployment Action"
description: "Creates a GitHub Deployment"
author: "chrnorm"
branding:
  icon: arrow-up
  color: black
inputs:
  initial_status:
    description: "Initial status for the deployment"
    default: "pending"
    required: false
  ref:
    description: "The reference for the deployment"
    required: false
  token:
    description: "Github repository token"
    required: true
  target_url:
    description: "Target url location"
    required: false
  description:
    description: "Descriptive message about the deployment"
    required: false
  environment:
    description: "The name of the environment for the deployment"
    default: "production"
    required: false
  auto_merge:
    description: "Sets the value of auto_merge for the deployment"
    default: "false"
    required: false
  payload:
    description: "Sets the payload for the deployment"
    default: ""
    required: false
  task:
    description: "Sets the task for the deployment"
    default: ""
    required: false
outputs:
  deployment_id:
    description: "The ID of the created deployment"
runs:
  using: "node12"
  main: "dist/index.js"
